# Generated by Django 5.2.5 on 2025-08-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tasksmodel_due_date_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodel',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
