# Generated by Django 5.2.5 on 2025-09-01 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tasksmodel_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
